### ISSUE TITLE
Nav page d'accueil peu lisible

### ISSUE THREAD

**Issue by virgile-dev** [CodeCitoyen/codecitoyen.github.io#1]
La police étant foncée ainsi que l'image de background on a du mal à lire les éléments de la nav

**Comment by Xalava** [comment]
juste, il faudrait que ça s'adapte à l'image ou un choix plus safe: bold...
Je viens de regarder, ça se passe dans responsive.css, il y a des instructions compilées de sass à démeller

**Comment by clairezed** [comment]
Je suis assez d'accord là-dessus, la landing page actuelle fonctionne pas. A la réflexion, je trouve que la  landing page alternative proposée par le thème fonctionne mieux, pour l'événement. Plus simple à manipuler. 

Ca pourrait donner un truc comme ça : https://codecitoyen.github.io/index-alt.html

De façon générale, si on veut pas s'emmerder à bidouiller trop le thème, il faut se forcer à choisir des illustrations très claires systématiquement, pour les background. Sur la page de contact, par exemple, ça marche pas trop (https://codecitoyen.github.io/contact.html). Si pas d'illustration top, j'aurais tendance à mettre plutôt des aplats de couleur, tant qu'à faire

**Comment by clemaurny** [comment]
Voici des images alternatives pour les villes, et le header plus visible (à tester)

https://github.com/clemaurny/codecitoyen.github.io/

**Comment by virgile-dev** [comment]
@clairezed c'est clair que la page d'accueil alt envoie carrément plus!

**Comment by virgile-dev** [comment]
Donc on switch sur la index-alt.html?
Votez 👍  si vous êtes ok @clairezed et @Xalava

**Comment by clairezed** [comment]
@clemaurny je re-débarque un peu, là. On peut voir en ligne directement ce que ça donne ? Je pensais que tu avais fait tes propositions directement sur ce projet, sur une autre branche ; pas sur un fork :)
Je passe quand même sans attendre sur la version alternative de la landing page. 

Par contre : il manque toujours des illustrations vraiment clean pour le slider d'accueil.

**Comment by clemaurny** [comment]
Oui, vous pouvez visualiser ça https://clemaurny.github.io/codecitoyen.github.io/

**Comment by Xalava** [comment]
@clemaurny Les images sont canons. J'ai une petite préférence pour la page d'accueil actuel, assez originale et dynamique. 
Pour les villes ton modèle est bien, "on discute" sur la page contact sort du cadre

**Comment by clemaurny** [comment]
Ok @xalava, le template alt-index rend bien en effet

**Comment by scenaristeur** [comment]
Le mer. 1 févr. 2017 22:23, Clement Lesaulnier <notifications@github.com> a
écrit :

> Oui, vous pouvez visualiser ça
> https://clemaurny.github.io/codecitoyen.github.io/
>
Hello, Clément, sur cette version, Le logo est coupé par le titre sur
mobile Android
