### ISSUE TITLE
Comment fait-on pour ajouter un partenaire dans le carrousel de la home?

### ISSUE THREAD

**Issue by virgile-dev** [CodeCitoyen/codecitoyen.github.io#14]
<img width="1246" alt="capture d ecran 2017-02-15 a 10 03 12" src="https://cloud.githubusercontent.com/assets/11473995/22967239/fd2f3fc0-f365-11e6-8974-ef173bae26c0.png">
Le logo qu'il faudrait que j'ajoute

![le_square](https://cloud.githubusercontent.com/assets/11473995/22967256/0ddf8352-f366-11e6-9103-5de28550a86b.jpg)

@Xalava

**Comment by Xalava** [comment]
image dans assets/images/partenaires, 
et lien dans la liste partenaire. Images environ 200px rectangulaire

**Comment by virgile-dev** [comment]
J'ai justement pas trouvé la liste partenaire... dsl

**Comment by Xalava** [comment]
corrigé avec 12dcbe94b925317c915008b6a6814afc1cd4ddb5
Il y a maintenant une liste partenaire par ville en + ( fin de l'entete)
